language: go
env:
  global:
    secure: RojNcqMzxj203Yx1fnZ4oHVsbZzfyadyqTWUiAmFzQaYGtLawvNjBsfcKQIajQFo/JdEG5uZp0yzBjS0XQfXDwtZeOLIuA35Ov6U44PuZ3CeSbcVBYPiQ1Abty8pEQyXuy9urnUEW6t/FgtSB7zB6Lqy6xH2SzUUKd7WC+n+Kxt7kAMwi9LGdWxi4vN9o6Pke4d3CRA8X5eb1/f2Q1egzDQIUDr7qgv2lpw8kTsb3rMMsgosnKLsGBV9ziLpe+SD48k9+wvzL5VzzKy+hlZqf8q2yIaEXskXjpHjoymc7jcTlO0mkO10AXCflY5VvrhE5/IvGdNBE0NKYwq5lJhpLs/a+PnA8tiUZYMPkkDQZLrBKZMFcJ2+WX/9iOkooF/kujfq+Zw5L1toYSw21IIImQLMLt36By5MCfHRVLj1lEqcH7r2g8l2ApxCKJgjf4dhVb9bjUTAbu6cbWfJ0tuxwelJMei7CP6iiSNFM0sO2vmCnmCOcmpeSgUt5WuISR5cXVElztFqdCtr9AyH3Clw8a6mesBrUYYik1Jk9PlnE+5mlhBJcWQ7khM0O5j1e81UzAYey8jNczV3guYwOoBW9cdDLKD+x1J4sOB4XzJkyiyha88J5b1g3EydEJI2Z+cLFt45IhC7blongiBnuqaNwdSEzx+6E5lZKUX+zWHgtjM=
go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip
install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
